CREATE TABLE "franchisees" (
	"id" serial PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"owner_name" text,
	"phone" text,
	"email" text,
	"address" text,
	"zone_name" text,
	"contract_type" text DEFAULT 'revenue_share' NOT NULL,
	"commission_rate" numeric(5, 2) DEFAULT '70',
	"platform_commission_rate" numeric(5, 2) DEFAULT '10',
	"monthly_fee" numeric(12, 2) DEFAULT '0',
	"status" text DEFAULT 'active' NOT NULL,
	"notes" text,
	"joined_at" timestamp DEFAULT now() NOT NULL,
	"contract_end_at" timestamp,
	"username" text,
	"password_hash" text,
	"last_login_at" timestamp,
	"affiliation_type" text DEFAULT 'affiliated' NOT NULL,
	"line_user_id" text,
	"google_id" text,
	"avatar_url" text,
	"contact_person" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "franchisees_code_unique" UNIQUE("code"),
	CONSTRAINT "franchisees_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "fusingao_fleets" (
	"id" serial PRIMARY KEY NOT NULL,
	"fleet_name" text NOT NULL,
	"contact_name" text,
	"contact_phone" text,
	"username" text NOT NULL,
	"password" text,
	"vehicle_types" text,
	"notes" text,
	"rate_override" numeric(12, 2),
	"commission_rate" numeric(5, 2) DEFAULT '15',
	"bank_name" text,
	"bank_account" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"fleet_type" text DEFAULT 'owner' NOT NULL,
	"fusingao_commission_rate" numeric(5, 2) DEFAULT '7',
	"monthly_affiliation_fee" numeric(10, 2) DEFAULT '0',
	"platform_fee_monthly" numeric(10, 2) DEFAULT '0',
	"contract_start_date" date,
	"contract_expire_date" date,
	"notes_internal" text,
	"has_tax_id" boolean DEFAULT false NOT NULL,
	"google_id" text,
	"avatar_url" text,
	"email" text,
	"line_id" text
);
--> statement-breakpoint
CREATE UNIQUE INDEX "franchisees_google_id_uidx" ON "franchisees" USING btree ("google_id") WHERE "franchisees"."google_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "fusingao_fleets_username_uidx" ON "fusingao_fleets" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX "fusingao_fleets_google_id_uidx" ON "fusingao_fleets" USING btree ("google_id") WHERE "fusingao_fleets"."google_id" IS NOT NULL;